### get goals
GET https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2NiwibmFtZSI6IllBWUFOIiwiZW1haWwiOiIxMTEyMDIzMTUwNjdAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgwOTY2Nzk3LCJleHAiOjE3ODEwNTMxOTd9.vlJcOZA0zIqo_e2KUvduoG-uBj1Pb_GPsv2elWIy_7E

### post goals
POST https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2NiwibmFtZSI6IllBWUFOIiwiZW1haWwiOiIxMTEyMDIzMTUwNjdAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgwOTY2Nzk3LCJleHAiOjE3ODEwNTMxOTd9.vlJcOZA0zIqo_e2KUvduoG-uBj1Pb_GPsv2elWIy_7E
Content-Type: application/json

{
  "target_amount": 5000,
  "present_amount": 2100
}